export const TOGGLE_TEMPERTURE_TYPE='TOGGLE_TEMPERTURE_TYPE';
export const TOGGLE_MODE='TOGGLE_MODE';
export const ADD_LOCATION_TO_FAVORITE='ADD_LOCATION_TO_FAVORITE';
export const REMOVE_LOCATION_FROM_FAVORITE='REMOVE_LOCATION_FROM_FAVORITE'